### ISSUE TITLE
What about PING option?

### ISSUE THREAD

**Issue by VarunBatraIT** [lgraubner/sitemap-generator-cli#15]
I was wondering if we have an option to ping to google and bing for newly created sitemap and thus encourage crawlers to crawl update ones.

This is an example: 

http://www.google.com/webmasters/sitemaps/ping?sitemap=http://www.yourdomain.com/sitemap.xml

**Comment by lgraubner** [comment]
I'd rather not include an option like this. There is no guarantee that the sitemap is available at the specified url after it is generated. What happens in that case?

**Comment by VarunBatraIT** [comment]
I agree with you. We are not accepting filename. Ping can thus only be used if we have a filename too. 

-output sitemap.xml -ping 

Assuming that base url option is compulsory. 

This makes npm module almost complete cli tool

**Comment by lgraubner** [comment]
Will have to think about this. Not sure how to handle the pipe output (current) and the filename option. Maybe there are some more opinions.

**Comment by lgraubner** [comment]
I decided against this option. I'm sorry. You can easily do it yourself like this:

```
sitemap-generator http://www.yourdomain.com sitemap.xml && curl http://www.google.com/webmasters/sitemaps/ping?sitemap=http://www.yourdomain.com/sitemap.xml
```

Even if the path is given (as it is now since v6) the generator can not know for sure where it is located. For example it could be `http://www.yourdomain.com/subfolder/sitemap.xml`. The generator does not know about `subfolder`.
